### ISSUE TITLE
Crash on MBP 16"

### ISSUE THREAD

**Issue by acrogenesis** [cyrus-and/zizzania#6] opened 2019-12-25 00:18 UTC
First of all thanks for this tool it helps automate lots of stuff. Recently I got my hands on a mbp 16" and it's crashing right when it finds the first client. Here's the crash log 

```
panic(cpu 6 caller 0xffffff800146520a): Kernel trap at 0xffffff7f82a2dbb8, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x0000000000003c6c, CR3: 0x00000006f5ed9041, CR4: 0x00000000003626e0
RAX: 0x0000000000003c5c, RBX: 0xffffff8050885000, RCX: 0xffffff7f82a2db9c, RDX: 0x0000000000000000
RSP: 0xffffff83bea13a80, RBP: 0xffffff83bea13a90, RSI: 0xffffff83b58e1d00, RDI: 0xffffff804e6e4000
R8:  0x0000000000000000, R9:  0x0000000000000000, R10: 0xffffff805aaa6310, R11: 0xffffff8001a42070
R12: 0xffffff83bea13b84, R13: 0xffffff804e8ada40, R14: 0xffffff83b58e1d00, R15: 0xffffff804e8ada40
RFL: 0x0000000000010246, RIP: 0xffffff7f82a2dbb8, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000003c6c, Error code: 0x0000000000000000, Fault CPU: 0x6, PL: 0, VF: 1

Backtrace (CPU 6), Frame : Return Address
0xffffff83bea134e0 : 0xffffff800133bb1b 
0xffffff83bea13530 : 0xffffff80014733e5 
0xffffff83bea13570 : 0xffffff8001464e5e 
0xffffff83bea135c0 : 0xffffff80012e2a40 
0xffffff83bea135e0 : 0xffffff800133b207 
0xffffff83bea136e0 : 0xffffff800133b5eb 
0xffffff83bea13730 : 0xffffff8001ad24f9 
0xffffff83bea137a0 : 0xffffff800146520a 
0xffffff83bea13920 : 0xffffff8001464f08 
0xffffff83bea13970 : 0xffffff80012e2a40 
0xffffff83bea13990 : 0xffffff7f82a2dbb8 
0xffffff83bea13a90 : 0xffffff7f820bddc4 
0xffffff83bea13ad0 : 0xffffff8001a423f5 
0xffffff83bea13b30 : 0xffffff7f820bdea8 
0xffffff83bea13b50 : 0xffffff7f820bd2a0 
0xffffff83bea13bb0 : 0xffffff7f820bd4ad 
0xffffff83bea13bf0 : 0xffffff7f82a2dc98 
0xffffff83bea13c20 : 0xffffff7f82a2db87 
0xffffff83bea13c40 : 0xffffff80015e77af 
0xffffff83bea13cd0 : 0xffffff80015d68e4 
0xffffff83bea13d50 : 0xffffff80015cace2 
0xffffff83bea13dc0 : 0xffffff80015bbd49 
0xffffff83bea13e20 : 0xffffff80018b7a00 
0xffffff83bea13ee0 : 0xffffff80018b77c0 
0xffffff83bea13f40 : 0xffffff800199acba 
0xffffff83bea13fa0 : 0xffffff80012e3206 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONetworkingFamily(3.4)[03C05ADC-CFE0-3B32-9305-5F17640F7B06]@0xffffff7f820aa000->0xffffff7f820d9fff
         com.apple.iokit.IO80211FamilyV2(1200.12.2b1)[B2B1D9BA-37A9-3F11-99DE-753D425C1C42]@0xffffff7f829a4000->0xffffff7f82b05fff
            dependency: com.apple.driver.corecapture(1.0.4)[5C346ED2-633E-32C2-8BD8-604F7D238B2B]@0xffffff7f8271b000
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[2FAEE793-59BC-3ADF-A5E2-3BC8760AFE0B]@0xffffff7f82421000
            dependency: com.apple.kec.corecrypto(1.0)[BDC53810-BC66-3B24-8F2B-EE3F9A7CF761]@0xffffff7f8233c000
            dependency: com.apple.iokit.IOSkywalkFamily(1)[402D50B6-F30F-38C5-A7ED-610AA11F2791]@0xffffff7f82799000
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[03C05ADC-CFE0-3B32-9305-5F17640F7B06]@0xffffff7f820aa000

BSD process name corresponding to current thread: zizzania
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19C57

Kernel version:
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
Kernel UUID: C3E7E405-C692-356B-88D3-C30041FD1E72
Kernel slide:     0x0000000001000000
Kernel text base: 0xffffff8001200000
__HIB  text base: 0xffffff8001100000
System model name: MacBookPro16,1 (Mac-E1008331FDC96864)
System shutdown begun: NO

System uptime in nanoseconds: 292800818433
last loaded kext at 34906373018: @kext.AMDRadeonX6100HWLibs	1.0 (addr 0xffffff7f85e63000, size 41893888)
loaded kexts:
com.intel.driver.EnergyDriver	3.6.1
@kext.AMDRadeonX6000	3.0.4
@kext.AMDRadeonServiceManager	3.0.4
>!AGraphicsDevicePolicy	4.5.21
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	4.5.21
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.2f4
>pmtelemetry	1
>!APlatformEnabler	2.7.0d0
>AGPM	111.4.1
>X86PlatformShim	1.0.0
@Dont_Steal_Mac_OS_X	7.0.0
>!AUpstreamUserClient	3.6.8
>AGDCBacklightControl	4.5.21
>ACPI_SMC_PlatformPlugin	1.0.0
>!A!IKBLGraphics	14.0.3
>BridgeAudioCommunication	6.60
>!AThunderboltIP	3.1.3
>!ABacklight	180.1
>!ATopCaseHIDEventDriver	3420.1
>!AHIDALSService	1
>!A!ICFLGraphicsFramebuffer	14.0.3
>!AAVEBridge	6.1
>!AFIVRDriver	4.1.0
>!AMuxControl2	4.5.21
>!ABridgeAudio!C	6.60
>!AGFXHDA	100.1.422
>!A!ISlowAdaptiveClocking	4.0.0
>!AMCCSControl	1.13
>!A!IPCHPMC	2.0.1
@filesystems.autofs	3.0
>BCMWLANFirmware4355.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>!ABCMWLANBusInterfacePCIe	1
>!AFileSystemDriver	3.0.1
@filesystems.hfs.kext	522.0.9
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
@filesystems.apfs	1412.61.1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
@kext.AMDRadeonX6100HWLibs	1.0
@kext.AMDRadeonX6000HWServices	3.0.4
|IOAVB!F	800.17
>!ASSE	1.0
@!AGPUWrangler	4.5.21
>IOPlatformPluginLegacy	1.0.0
>!AHDA!C	283.15
|IOHDA!F	283.15
@kext.AMDRadeonX6000Framebuffer	3.0.4
>!ABacklightExpert	1.1.0
>!AActuatorDriver	3420.2
>!AHS!BDriver	3420.1
>IO!BHIDDriver	7.0.2f4
>!AMultitouchDriver	3420.2
>!AInputDeviceSupport	3420.4
>!AHIDKeyboard	209
>!ASMBusPCI	1.0.14d1
>X86PlatformPlugin	1.0.0
|IOAccelerator!F2	438.2.8
>!AThunderboltEDMSink	4.2.2
>!AThunderboltDPOutAdapter	6.2.4
>!AGraphicsControl	4.5.21
|IONDRVSupport	569.3
|IO!BHost!CUARTTransport	7.0.2f4
|IO!BHost!CTransport	7.0.2f4
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
@kext.AMDSupport	3.0.4
@!AGraphicsDeviceControl	4.5.21
|IOSlowAdaptiveClocking!F	1.0.0
>!ASMBus!C	1.0.18d1
|IOGraphics!F	569.3
>IOPlatformPlugin!F	6.0.0d8
@plugin.IOgPTPPlugin	800.14
|IOEthernetAVB!C	1.1.0
@kext.triggers	1.0
>usb.IOUSBHostHIDDevice	1.2
>usb.cdc.ecm	5.0.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABCMWLANCore	1.0.0
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
|IO80211!FV2	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
|IOSurface	269.6
@filesystems.hfs.encodings.kext	1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
>!AXsanScheme	3
>usb.!UVHCIBCE	1.2
>usb.!UVHCI	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!AThunderboltPCIDownAdapter	2.5.2
>!AThunderboltDPInAdapter	6.2.4
>!AThunderboltDPAdapter!F	6.2.4
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
>!A!ILpssI2C	3.0.60
>!AThunderboltNHI	5.8.1
|IOThunderbolt!F	7.4.7
>usb.!UHostPacketFilter	1.0
|IOUSB!F	900.4.2
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!AKeyStore	2
>!UTDM	489.60.3
|IOSCSIBlockCommandsDevice	422.0.2
>!ACredentialManager	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|CoreAnalytics!F	1
|IOTimeSync!F	800.14
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	7.0.2f4
|IO!BPacketLogger	7.0.2f4
|IOUSBMass!SDriver	157.40.7
|IOSCSIArchitectureModel!F	422.0.2
|IO!S!F	2.1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!UHostMergeProperties	1.2
>!ABusPower!C	1.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
```

**Comment by cyrus-and** [comment] 2019-12-25 10:22
Let me try to reproduce this. In the meantime, does this also happen when reading from file (`-r` option)? Also please provide the full command line that caused the crash. Thank you.

**Comment by cyrus-and** [comment] 2019-12-25 10:56
> First of all thanks for this tool it helps automate lots of stuff. 

I'm glad to hear that! :)

I cannot reproduce the crash here:

    Darwin Kernel Version 19.2.0

**Comment by acrogenesis** [comment] 2019-12-25 22:18
Running using `-r` on a file with handshakes doesn't crash the computer.

I'm using `sudo zizzania -i en0  -b bssid -w wifi.pcap`
```
uname -a
Darwin adrians-mbp.lan 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```

**Comment by cyrus-and** [comment] 2019-12-26 11:59
Thanks, a few more questions. I suspect this is about the injection capability of your setup.

1. Does this happen 100% of the times in the scenario you describe?

2. Does this happen with the `-n` option too?

3. Can you show me the model information from About This Mac? Here's mine:

    ```
    MacBook Pro (Retina, 15-inch, Mid 2014)
    ```

4. Can you show me the content of System Information -> Network -> Wi-Fi? Feel free to omit the "Current Network Information" and redact your MAC Address. Here's mine:

    ```
    Software Versions:
     CoreWLAN:  13.0 ((null))
     CoreWLANKit:  13.0 ((null))
     Menu Extra:  13.0 ((null))
     System Information:  12.0 (1355)
     IO80211 Family:  12.0 (1200.12.2b1)
     Diagnostics:  1.0 (910)
     AirPort Utility:  Not Installed
     Interfaces:
    en0:
     Card Type:  AirPort Extreme  (0x14E4, 0x134)
     Firmware Version:  Broadcom BCM43xx 1.0 (7.77.106.3 AirPortDriverBrcmNIC-1435.3)
     MAC Address:  REDACTED
     Locale:  ETSI
     Country Code:  DE
     Supported PHY Modes:  802.11 a/b/g/n/ac
     Supported Channels:  1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 149, 153, 157, 161
     Wake On Wireless:  Supported
     AirDrop:  Supported
     AirDrop Channel:  44
     Auto Unlock:  Supported
     Status:  Connected
    ```

**Comment by acrogenesis** [comment] 2019-12-26 19:32
1. Happens every time, it freezes fans go 100% after a second it reboots
2. It seems with -n it does work and gets new clients successfully
3. MacBook Pro (16-inch, 2019)
4.
```
  Software Versions:
  CoreWLAN:	13.0 ((null))
  CoreWLANKit:	13.0 ((null))
  Menu Extra:	13.0 ((null))
  System Information:	12.0 (1355)
  IO80211 Family:	12.0 (1200.12.2b1)
  Diagnostics:	1.0 (910)
  AirPort Utility:	Not Installed
  Interfaces:
en0:
  Card Type:	AirPort Extreme  (0x14E4, 0x7BF)
  Firmware Version:	wl0: Oct 26 2019 10:24:57 version 9.112.2.0.32.5.40 FWID 01-95c65950
  MAC Address:	f8:ff:c2:49:b7:4b
  Locale:	FCC
  Country Code:	X0
  Supported PHY Modes:	802.11 a/b/g/n/ac
  Supported Channels:	1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 36, 40, 44, 48, 52, 56, 60, 64, 100, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 149, 153, 157, 161, 165
  Wake On Wireless:	Supported
  AirDrop:	Supported
  AirDrop Channel:	0
  Auto Unlock:	Supported
  Status:	Not Associated
```

**Comment by cyrus-and** [comment] 2019-12-27 12:43
I tried googling your issue and apparently many have similar problems, for example it's known that `aireplay-ng` crashes on MacBooks, this is weird, the injection works perfectly with mine (Mid 2014) and by the way I simply call `pcap_inject` so I'm afraid there's nothing I can do about it.

Consider that a MacBook might not be the best choice for this kind of things, another pretty common issue (that I too have) is that the received packets are severely garbled in monitor mode and this also happens in Wireshark; you'll notice several MAC addresses that are the same except for a few bytes.

Unfortunately I don't have any 2019 MacBooks to try this on.

**Comment by cyrus-and** [comment] 2019-12-28 19:08
I remember that before introducing the support for monitor mode on macOS I used a Wi-Fi USB dongle and a Linux VM, worked flawlessly, it's better than nothing if you are forced to use that MacBook.

I'm closing this but feel free to comment if you come up with something.

Good luck!

**Closed by cyrus-and** 2019-12-28 19:08 UTC

**Comment by montali** [comment] 2020-11-13 17:44
I second this! MBP 15" 2019, kernel panics after finding a client :( 
Does anybody have any ideas on what to try?
